name: Node CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    uses: voxpelli/ghatemplates/.github/workflows/test-pg.yml@main
    with:
      node-versions: '18,20,22'
      os: 'ubuntu-latest'
      pg-versions: '9.6,12,13'
